"""
app.py — Flask REST API backend for DukeGuessr.

What this file does:
    Loads all three models at startup (fine-tuned CLIP, zero-shot CLIP,
    fine-tuned ViT) and serves a single /predict endpoint that runs an
    uploaded image through all three in one request. Returns a structured
    JSON response with each model's prediction, confidence scores, and
    all-class probability distributions for side-by-side comparison in
    the frontend. The fine-tuned CLIP result additionally includes a
    "brightness_map" field: a base64-encoded PNG where pixel brightness
    reflects the model's per-patch attention weights, generated via a
    forward hook on the last ViT-B/32 transformer block at zero extra
    inference cost.

Academic contributions demonstrated here:
    - Deployment of trained ML models as a functional web application with
      a user interface. The Flask API bridges the PyTorch inference code
      and the React frontend, enabling real-time single-image classification
      through a browser.
    - Multi-model serving: all three architectures (fine-tuned CLIP,
      zero-shot CLIP, fine-tuned ViT) are loaded once at startup and kept
      in memory, allowing the frontend to display a live architecture
      comparison on every uploaded image.
    - The zero-shot CLIP model is loaded from base pretrained weights with
      no fine-tuned checkpoint. Its text features are encoded from the
      same landmark descriptions used in training, making the comparison
      between zero-shot and fine-tuned CLIP a controlled experiment.
    - Serving the attention brightness map: the /predict response for
      fine-tuned CLIP includes a base64-encoded PNG generated by
      predict.py's attention hook. The API transports this as a JSON
      string, which the frontend decodes and renders directly as an
      <img> element with no additional requests.

AI attribution: This file was scaffolded with Claude (Anthropic). The multi-model
architecture decision, port 5001 workaround for macOS AirPlay, and all deployment
design decisions are Alexander Zarboulas's original work. See ATTRIBUTION.md for full details.

Startup:
    python src/app.py \
        --clip_weights models/clip_base_best.pth \
        --vit_weights  models/vit_base_best.pth  \
        --descriptions data/descriptions/landmarks.json \
        --port 5001

    Note: macOS AirPlay occupies port 5000. Use --port 5001.
"""

import argparse
import os

import torch
from flask import Flask, jsonify, request
from flask_cors import CORS

from predict import predict as clip_predict, predict_vit

app = Flask(__name__)
CORS(app)  # Allow cross-origin requests from the React frontend

# 16 MB upload limit — sufficient for high-resolution JPEGs from modern cameras
app.config["MAX_CONTENT_LENGTH"] = 16 * 1024 * 1024

ALLOWED_EXTENSIONS = {"jpg", "jpeg", "png", "webp"}

# ── Global model state ────────────────────────────────────────────────────────
# All three models are loaded once at startup and held in module globals.
# This avoids re-loading weights (slow) on every request.
_ft_clip_model    = None   # fine-tuned CLIP image encoder
_ft_clip_features = None   # (7, 512) text embeddings for fine-tuned CLIP
_zs_clip_model    = None   # base CLIP, no fine-tuning (zero-shot)
_zs_clip_features = None   # (7, 512) text embeddings for zero-shot CLIP
_vit_model        = None   # fine-tuned ViT-B/16
_device           = None


def _allowed(filename: str) -> bool:
    """Return True if the file extension is in the allowed set."""
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


# ── Routes ────────────────────────────────────────────────────────────────────
@app.route("/predict", methods=["POST"])
def predict_route():
    """
    Accept a multipart image upload and return predictions from all three models.

    Request:  POST /predict with form field "image" containing an image file.
    Response: JSON with keys "finetuned_clip", "zeroshot_clip", "finetuned_vit",
              each containing the model's full result dict (landmark, confidence,
              lat/lon, is_other, all_predictions). The "finetuned_clip" result
              additionally includes "brightness_map": a base64-encoded PNG where
              brighter pixels indicate patches the model attended to most when
              forming its prediction. Zero-shot CLIP and ViT results do not
              include a brightness map.

    Running all three models per request allows the frontend to switch between
    model views without making additional API calls.
    """
    if "image" not in request.files:
        return jsonify({"error": "No image field in request"}), 400

    file = request.files["image"]
    if file.filename == "" or not _allowed(file.filename):
        return jsonify({"error": "Invalid or missing file"}), 400

    # Read bytes once — reused across all three model calls
    image_bytes = file.read()

    return jsonify({
        "finetuned_clip": clip_predict(_ft_clip_model, _ft_clip_features,
                                       image_bytes, _device),
        "zeroshot_clip":  clip_predict(_zs_clip_model, _zs_clip_features,
                                       image_bytes, _device),
        "finetuned_vit":  predict_vit(_vit_model, image_bytes, _device),
    })


@app.route("/health", methods=["GET"])
def health():
    """Simple liveness check — returns 200 if the server is up and models are loaded."""
    return jsonify({"status": "ok"})


# ── Model loading ─────────────────────────────────────────────────────────────
def load_models(clip_weights: str, vit_weights: str, descriptions_path: str):
    """
    Load all three models into memory at server startup.

    Fine-tuned CLIP:
        Loads the base ViT-B/32 CLIP architecture and overwrites its weights
        with the fine-tuned checkpoint. Text features are encoded from the
        landmark paragraphs using the fine-tuned model's text encoder.

    Zero-shot CLIP:
        Loads the base ViT-B/32 CLIP with no checkpoint — purely pretrained
        weights. Text features are encoded separately so the zero-shot model
        has its own (7, 512) anchor matrix. Using the same landmark paragraphs
        as text anchors keeps the comparison controlled.

    Fine-tuned ViT:
        Loads the ViT-B/16 architecture with the 7-class head and overwrites
        weights from the fine-tuned checkpoint.
    """
    global _ft_clip_model, _ft_clip_features
    global _zs_clip_model, _zs_clip_features
    global _vit_model, _device

    from clip_model import load_clip, load_finetuned_clip, encode_descriptions
    from vit_model import build_vit, load_checkpoint

    _device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Fine-tuned CLIP — loads checkpoint, encodes text features with fine-tuned weights
    _ft_clip_model, _ft_clip_features = load_finetuned_clip(
        clip_weights, _device, descriptions_path
    )
    print("Fine-tuned CLIP loaded.")

    # Zero-shot CLIP — base pretrained weights only, no checkpoint
    _zs_clip_model, _ = load_clip(_device)
    _zs_clip_model.to(_device).eval()
    # Encode text features with the base model's text encoder
    _zs_clip_features = encode_descriptions(_zs_clip_model, descriptions_path, _device)
    print("Zero-shot CLIP loaded.")

    # Fine-tuned ViT — loads checkpoint into a fresh build_vit() instance
    _vit_model = load_checkpoint(vit_weights, build_vit(), _device)
    _vit_model.eval()
    print("Fine-tuned ViT loaded.")

    print(f"All models ready. Device: {_device}")


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--clip_weights",  required=True,
                        help="Path to fine-tuned CLIP weights (.pth)")
    parser.add_argument("--vit_weights",   required=True,
                        help="Path to fine-tuned ViT weights (.pth)")
    parser.add_argument("--descriptions",  default="data/descriptions/landmarks.json",
                        help="Path to landmark text descriptions JSON")
    parser.add_argument("--port",          type=int, default=5001,
                        help="Port to serve on (default 5001; macOS AirPlay uses 5000)")
    args = parser.parse_args()

    for p in (args.clip_weights, args.vit_weights):
        if not os.path.exists(p):
            raise FileNotFoundError(f"Weights not found: {p}")

    load_models(args.clip_weights, args.vit_weights, args.descriptions)
    app.run(debug=False, port=args.port)
